# Header
menu:
  主页: /
  归档: /archives

menucount: 归档
comment_provider: duoshuo
# Duoshuo comment
duoshuo:
  short_name: dmxiaoshen

# Content
excerpt_link: 阅读全文 >
fancybox: true
baidu_tongji: dmxiaoshen

categorie1: 随写
categorie2: 笔记
categorie3: 图集
